version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: hangman-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: spanish_hangman
    ports:
      - "3306:3306"	
  hangman-backend:
    build: .
    container_name: hangman-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/spanish_hangman?createDatabaseIfNotExist=true
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db